### PR TITLE
fix reset cmd

### LINKED ISSUE #2282: kubefirst reset fails when .kubefirst file is not present
### Which version of kubefirst are you using?

v2.6.0

### Which cloud provider?

None specific

### Which DNS?

None specific

### Which installation type?

None specific

### Which distributed Git provider?

None specific

### Did you use a fork of `gitops-template`?

No

### Which Operating System?

macOS

### What is the issue?

kubefirst reset should guard against directories and files not being present:

```
➜  ~ kubefirst version  
                                                                              
                                                                              
  kubefirst-cli golang utility version: v2.6.0                                


➜  ~ kubefirst reset  
Error: unable to determine contents of kubefirst-checks: unexpected type <nil>

If a detailed error message was available, please make the necessary corrections before retrying.
You can re-run the last command to try the operation again.

➜  ~ rm -rf ~/.k1 ~/.kubefirst
➜  ~ kubefirst reset          
Error: unable to determine contents of kubefirst-checks: unexpected type <nil>

If a detailed error message was available, please make the necessary corrections before retrying.
You can re-run the last command to try the operation again.


```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jokestax**
## Description
Handle the nil value of viperfile content

## Related Issue(s)

Fixes #2282 

## How to test
build the binary and run "./kubefirst reset"

### CODE REVIEW

**Review by johndietz — DISMISSED** [review]

File: cmd/reset.go [hunk 1]
```diff
@@ -30,6 +31,13 @@ var resetCmd = &cobra.Command{
 		cloudProvider := viper.GetString("kubefirst.cloud-provider")
 
 		checksMap := viper.Get("kubefirst-checks")
+		if checksMap == nil {
+			in := `# Succesfully reset`
+			out, _ := glamour.Render(in, "dark")
+			fmt.Print(out)
+			progress.Progress.Quit()
+			return nil
+		}
```
Comment (patrickdappollonio) [inline cmd/reset.go:40]: Down below there seems to be a switch on the type, which could have the type to be empty (`nil`).

Do we need to quit if we can't find it? Or perhaps we need to ignore it if it's not there but continue with the cleanup after?

**Review by patrickdappollonio — CHANGES_REQUESTED** [review]

File: cmd/reset.go (hunk 1 above)
Comment (patrickdappollonio) [reply cmd/reset.go:40]: Strange, because right down below, it says "if the map is a string, and that string is empty, log a message but continue".

What makes the map being nil vs being empty different?

File: cmd/reset.go [hunk 2]
```diff
@@ -30,6 +31,13 @@ var resetCmd = &cobra.Command{
 		cloudProvider := viper.GetString("kubefirst.cloud-provider")
 
 		checksMap := viper.Get("kubefirst-checks")
+		if checksMap == nil {
+			in := `# Succesfully reset`
+			out, _ := glamour.Render(in, "dark")
+			fmt.Print(out)
+			progress.Progress.Quit()
+			return nil
```
Comment (CristhianF7) [inline cmd/reset.go]: Please use the progress success function

```suggestion
		message := `# Succesfully reset`
		progress.Success(message)
```

**Review by CristhianF7 — CHANGES_REQUESTED** [review]

File: cmd/reset.go (hunk 1 above)
Comment (jokestax) [reply cmd/reset.go]: if we have .kubefirst file present,then in that file we will have "kubefirst-checks" as one of the fields,which will be set to empty as "kubefirst-checks:""' and we run a reset cmd,however when we dont have that file present at all go thows nil error

Comment (jokestax) [reply cmd/reset.go]: we can remove the else in case string ig

**Review by patrickdappollonio — APPROVED** [review]

**Review by CristhianF7 — APPROVED** [review]
